name: clang-format-checker

on: push

jobs:
  check_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check if script returns 1
      run: |
        set +x
        ./ci/clang-format-checker.sh
        exit_code=$?

        if [ $exit_code -eq 1 ]; then
          exit 1
        else
          echo "Merging is allowed."
        fi